POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "monica",
    "email": "monicaaraujo@gmail.com",
    "password": "1235678"
}

###

# @name login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "monicaaraujo@gmail.com",
    "password": "1235678"
}

###

# @name getProfile
GET  http://localhost:3003/users/profile
Authorization: {{login.response.body.token}}

###

GET http://localhost:3003/users/{{getProfile.response.body.id}}/profile
Authorization: {{login.response.body.token}}